### ISSUE TITLE
New PySimpleGUI layout controls may be of interest

### ISSUE THREAD

**Issue by PySimpleGUI** [boo13/xcv#2]
The 4.3 release of PySimpleGUI (tkinter version though) has more layout capabilities than previously.  You can now justify elements in all of the containers or at the Window level.  This makes centering and other such alignments must easier / possible than before.

The changes will eventually migrate to the other 3 ports I'm sure, just not sure exactly when.

Are you using Qt because you're on a Mac?

**Comment by boo13** [comment]
Been exploring these options - and I like the way the updated versions work, but alas, I am using Qt in an attempt to maintain Mac compatibility (I switch between Mac and PC often), though we'll see how long that lasts now that I'm getting into more and more cases where maintaining both is causing problems.
